//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatSI.UPServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UPServer.PatSISvsSoap")]
    public interface PatSISvsSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 getLastVersionResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastVersion", ReplyAction="*")]
        PatSI.UPServer.getLastVersionResponse getLastVersion(PatSI.UPServer.getLastVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWebHostDateTime", ReplyAction="*")]
        System.DateTime getWebHostDateTime();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastVersion", Namespace="http://tempuri.org/", Order=0)]
        public PatSI.UPServer.getLastVersionRequestBody Body;
        
        public getLastVersionRequest() {
        }
        
        public getLastVersionRequest(PatSI.UPServer.getLastVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getLastVersionRequestBody {
        
        public getLastVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public PatSI.UPServer.getLastVersionResponseBody Body;
        
        public getLastVersionResponse() {
        }
        
        public getLastVersionResponse(PatSI.UPServer.getLastVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLastVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLastVersionResult;
        
        public getLastVersionResponseBody() {
        }
        
        public getLastVersionResponseBody(string getLastVersionResult) {
            this.getLastVersionResult = getLastVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatSISvsSoapChannel : PatSI.UPServer.PatSISvsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatSISvsSoapClient : System.ServiceModel.ClientBase<PatSI.UPServer.PatSISvsSoap>, PatSI.UPServer.PatSISvsSoap {
        
        public PatSISvsSoapClient() {
        }
        
        public PatSISvsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatSISvsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatSISvsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatSISvsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PatSI.UPServer.getLastVersionResponse PatSI.UPServer.PatSISvsSoap.getLastVersion(PatSI.UPServer.getLastVersionRequest request) {
            return base.Channel.getLastVersion(request);
        }
        
        public string getLastVersion() {
            PatSI.UPServer.getLastVersionRequest inValue = new PatSI.UPServer.getLastVersionRequest();
            inValue.Body = new PatSI.UPServer.getLastVersionRequestBody();
            PatSI.UPServer.getLastVersionResponse retVal = ((PatSI.UPServer.PatSISvsSoap)(this)).getLastVersion(inValue);
            return retVal.Body.getLastVersionResult;
        }
        
        public System.DateTime getWebHostDateTime() {
            return base.Channel.getWebHostDateTime();
        }
    }
}
